openapi: 3.0.3
info:
  title: Recommend API
  description: |-
    This is a API for [recommend-api](https://github.com/kkday-it/kkday-recommend-api)
  version: 1.0.0
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: https://recommend.sit.kkday.com
tags:
  - name: order_list
    description: 訂購頁
paths:
  /v3/recommend/order_list/mixed:
    get:
      tags:
        - order_list
      summary: 訂單管理頁 - 混合版位
      parameters:
        - name: device_id
          in: query
          schema:
            type: string
            nullable: true
            example: TOY68TOY-0204-4264-8764-E4B7D21438DC
        - name: member_uuid
          in: query
          schema:
            type: string
            nullable: true
            example: 20ctoy42-4264-4ee7-ev8d-ea8toyf9617a
        - name: locale
          in: query
          required: true
          schema:
            type: string
            example: tw
            enum:
              - kk
              - sg
              - ph
              - id
              - jp
              - kr
              - th
              - vn
              - cn
              - my
              - hk
              - tw
              - au
              - nz
              - us
        - name: source
          in: query
          required: True
          schema:
            type: string
            enum:
              - web
              - mweb
              - ios
              - android
            example: web
        - name: lang
          in: query
          required: true
          schema:
            type: string
            example: zh-tw
            enum:
              - en
              - ja
              - ko
              - th
              - vi
              - zh-cn
              - zh-hk
              - zh-tw
        - name: cid
          in: query
          schema:
            type: string
            nullable: true
        - name: ud1
          in: query
          schema:
            type: string
            nullable: true
        - name: ud2
          in: query
          schema:
            type: string
            nullable: true
        - name: ip
          in: query
          schema:
            type: string
            nullable: true
          example: "8.8.8.8"
        - name: currency
          in: query
          required: true
          description: 幣別
          schema:
            type: string
            example: TWD
        - name: count
          in: query
          schema:
            type: integer
            default: 5
          description: "數量預設為5"
        - name: orders
          in: body
          required: true
          schema:
            type: array
            items:
              type: object
              properties:
                country_keys:
                  type: array
                  items:
                    type: string
                    example: A01-001
                city_keys:
                  type: array
                  description: kkday城市
                  items:
                    type: string
                    example: A01-001-00001
                order_mid:
                  type: string
                  example: "23KK123456789"
                cat_keys:
                  type: array
                  items:
                    type: string
                    example: TAG_3_4
                prod_mid:
                  type: string
                  default: 1781
                order_date:
                  type: string
                  example: "20230818"
                back_date:
                  type: string
                  example: "20230825"
                  description: 結束日期
                status:
                  type: string
                  example: "GO"
                timezone:
                  type: string
                  example: "Asia/Taipei"
                  description: "時區"
          description: 訂單
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  metadata:
                    type: object
                    properties:
                      status:
                        type: string
                        example: "0000"
                      desc:
                        type: string
                        example: Success
                  data:
                    type: object
                    properties:
                      order_mid:
                        type: string
                        example: 23KK123456789
                      mixed_recommend:
                        type: array
                        example: [
                          {
                            "name": "product",
                            "data": {
                              "id": 109961,
                              "prod_oid": 109961,
                              "name": "桃園青埔|Xpark 都會型水生公園門票",
                              "introduction": "由日本橫濱八景島首度跨海來台桃園開設分館「Xpark」...",
                              "rating_count": 1000,
                              "rating_star": 4,
                              "order_count": 100,
                              "confirm_hour": 0,
                              "instant_booking": true,
                              "instant_use": true,
                              "free_refund_policy": true,
                              "free_refund_before_day": 8,
                              "earliest_sale_date": 20221109,
                              "sale_status": 1,
                              "purchase_type": null,
                              "purchase_date": 20221109,
                              "is_tourism_product": true,
                              "readable_url": null,
                              "main_cat_key": "M05",
                              "promo_tag_keys": [
                                  "string"
                              ],
                              "cat_key": [
                                  "TAG_3_4"
                              ],
                              "theme_code": [
                                  "string"
                              ],
                              "product_labels": [
                                  "string"
                              ],
                              "img_url": "https://img.sit.kkday.com/image/jpg",
                              "img_url_list": [
                                  "https://img.sit.kkday.com/image/jpg"
                              ],
                              "durationt": 120,
                              "days": 0,
                              "hours": 2,
                              "minutes": 0,
                              "currency": "TWD",
                              "display_sale_price": 500,
                              "sale_price": 500,
                              "display_price": 1255,
                              "price": 1255,
                              "discount": -1.51,
                              "is_display_price": false,
                              "app_cheaper_than_web": false,
                              "max_price": 13231232,
                              "countries": [
                                  {
                                      "id": "A01-001",
                                      "name": "台灣",
                                      "cities": [
                                          {
                                              "id": "A01-001-00001",
                                              "name": "台北"
                                          }
                                      ]
                                  }
                              ],
                              "is_marketplace": false,
                              "supplier_oid_list": [
                                  10693
                              ],
                              "supplier_name": "string",
                              "supplier_logo": "string",
                              "supplier_award": 0,
                              "is_zero_price": false
                            }
                          },
                          {
                            "name": "category_icon",
                            "data": {
                                "id": "rec_cat_8",
                                "name": "機場接駁",
                                "location": {
                                  "name": "桃園"
                                },
                                "show_order_count": "95K+",
                                "img_url": "https://cdn.kkday.com/ds/picto_cat_healthRelaxation.png",
                                "link": "https://www.sit.kkday.com/zh-hk/product/productlist/?cat=TAG_5_2&city=A01-001-00008"
                            }
                          }
                        ]
                      location:
                        type: object
                        properties:
                          key:
                            type: string
                            default: A01-001-00001
                          name:
                            type: string
                            example: 台北